-- MySQL Script generated by MySQL Workbench
-- Wed Dec  9 20:32:24 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET latin2 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`airline_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`airline_info` (
  `airline_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `arrive` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `departure` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`airline_id`)  COMMENT '',
  UNIQUE INDEX `airline_id_UNIQUE` (`airline_id` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 5011
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `cust_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `fname` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `lname` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `address` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`cust_id`)  COMMENT '',
  UNIQUE INDEX `cust_id_UNIQUE` (`cust_id` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 111
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`booking` (
  `booking_num` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `customer_cust_id` INT(11) NOT NULL COMMENT '',
  `airline_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`booking_num`)  COMMENT '',
  UNIQUE INDEX `booking_num_UNIQUE` (`booking_num` ASC)  COMMENT '',
  INDEX `fk_booking_customer_idx` (`customer_cust_id` ASC)  COMMENT '',
  INDEX `fk_booking_airline_idx` (`airline_id` ASC)  COMMENT '',
  CONSTRAINT `fk_booking_customer`
    FOREIGN KEY (`customer_cust_id`)
    REFERENCES `mydb`.`customer` (`cust_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1027
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`plane_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`plane_info` (
  `plane_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `model` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `seats` INT(11) NULL DEFAULT NULL COMMENT '',
  `airline_info_airline_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`plane_id`, `airline_info_airline_id`)  COMMENT '',
  UNIQUE INDEX `plane_id_UNIQUE` (`plane_id` ASC)  COMMENT '',
  INDEX `fk_plane_info_airline_info1_idx` (`airline_info_airline_id` ASC)  COMMENT '',
  CONSTRAINT `fk_plane_info_airline_info1`
    FOREIGN KEY (`airline_info_airline_id`)
    REFERENCES `mydb`.`airline_info` (`airline_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`corporation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`corporation` (
  `corp_code` VARCHAR(45) NOT NULL COMMENT '',
  `corp_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `location` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `plane_info_plane_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`corp_code`)  COMMENT '',
  UNIQUE INDEX `corp_id_UNIQUE` (`corp_code` ASC)  COMMENT '',
  INDEX `fk_corporation_plane_info1_idx` (`plane_info_plane_id` ASC)  COMMENT '',
  CONSTRAINT `fk_corporation_plane_info1`
    FOREIGN KEY (`plane_info_plane_id`)
    REFERENCES `mydb`.`plane_info` (`plane_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`discount` (
  `discount_rate` FLOAT NULL DEFAULT NULL COMMENT '',
  `customer_cust_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`customer_cust_id`)  COMMENT '',
  CONSTRAINT `fk_discount_customer1`
    FOREIGN KEY (`customer_cust_id`)
    REFERENCES `mydb`.`customer` (`cust_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`distance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`distance` (
  `miles` INT(11) NULL DEFAULT NULL COMMENT '',
  `airline_info_airline_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`airline_info_airline_id`)  COMMENT '',
  CONSTRAINT `fk_distance_airline_info1`
    FOREIGN KEY (`airline_info_airline_id`)
    REFERENCES `mydb`.`airline_info` (`airline_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`price` (
  `price_airline` INT(11) NULL DEFAULT NULL COMMENT '',
  `airline_info_airline_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`airline_info_airline_id`)  COMMENT '',
  CONSTRAINT `fk_price_airline_info1`
    FOREIGN KEY (`airline_info_airline_id`)
    REFERENCES `mydb`.`airline_info` (`airline_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
